"""
Django settings for backend project with centralized JWT authentication.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/
"""

from pathlib import Path
from decouple import config
import os
import requests
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_FILE_DIR = "/var/szDirectoryName/Data/"

# Quick-start development settings - unsuitable for production
SECRET_KEY = config("SECRET_KEY")
DEBUG = True
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# URLs
BASE_URL = config('BASE_URL', default='0.0.0.0:8000')
DSS_API = config('DSS_API', default='0.0.0.0:248')
FRONTEND_URL = config('FRONTEND_URL', default='0.0.0.0:3000')

# Legacy system credentials
ALIGNSYS_LOGIN = config("ALIGNSYS_LOGIN", "")
ALIGNSYS_PWD = config("ALIGNSYS_PWD", "")

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts', 
    'rest_framework',             
    'app',
    'corsheaders',
    'phone_field',
    'crispy_forms',
    'widget_tweaks',
]

# --- REST Framework configuration ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CentralizedJWTAuthentication',  # Custom centralized JWT
        'rest_framework.authentication.SessionAuthentication',   # Optional: admin login
    ),
}

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# --- Centralized Auth API configuration ---
CENTRAL_AUTH_API = {
    "BASE_URL": config("CENTRAL_AUTH_BASE_URL", default="http://localhost:8000"),
    "TOKEN_VERIFY_ENDPOINT": "/api/token/verify/",   # token validation endpoint
    "TOKEN_REFRESH_ENDPOINT": "/api/token/refresh/", # optional refresh endpoint
    "SECRET_KEY": config("CENTRAL_AUTH_SECRET", default=""),  # optional local verification
}

# Middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
   'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'NAME': config("DB_NAME"),
      'USER': config("DB_USERNAME"),
      'PASSWORD': config("DB_PASSWORD"),
      'HOST': config("DB_HOST"),
      'PORT': config("DB_PORT", cast=int),
   }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# Static and media files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True

# CORS & CSRF
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = config('CORS_ORIGINS', default='').split(',')
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',')

# SMTP Email (Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST_GMAIL')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER_GMAIL')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD_GMAIL')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL_GMAIL')